module.exports = {
  'IMSB': '/assets/types/IMSB.jpg',
  'BOSS': '/assets/types/BOSS.jpg',
  'MUM': '/assets/types/MUM.jpg',
  'FAKE': '/assets/types/FAKE.jpg',
  'DEAD': '/assets/types/DEAD.jpg',
  'ZZZZ': '/assets/types/ZZZZ.jpg',
  'GOGO': '/assets/types/GOGO.jpg',
  'FUCK': '/assets/types/FUCK.jpg',
  'CTRL': '/assets/types/CTRL.jpg',
  'HHHH': '/assets/types/HHHH.jpg',
  'SEXY': '/assets/types/SEXY.jpg',
  'OJBK': '/assets/types/OJBK.jpg',
  'POOR': '/assets/types/POOR.jpg',
  'OH-NO': '/assets/types/OH_NO.jpg',
  'MONK': '/assets/types/MONK.jpg',
  'SHIT': '/assets/types/SHIT.jpg',
  'THAN-K': '/assets/types/THAN_K.jpg',
  'MALO': '/assets/types/MALO.jpg',
  'ATM-er': '/assets/types/ATM_er.jpg',
  'THIN-K': '/assets/types/THIN_K.jpg',
  'SOLO': '/assets/types/SOLO.jpg',
  'LOVE-R': '/assets/types/LOVE_R.jpg',
  'WOC!': '/assets/types/WOC.jpg',
  'DRUNK': '/assets/types/DRUNK.jpg',
  'IMFW': '/assets/types/IMFW.jpg',
};


